name: flutter_redux
description: A set of utility Widgets that Provide and Connect to a Redux Store
version: 0.8.2
homepage: https://github.com/brianegan/flutter_redux

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ">=5.0.0 <6.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
